### ISSUE TITLE
Cannot find module "fs-extra"

### ISSUE THREAD

**Issue by RikkiGibson** [docscript/docscript#52]
Repro:

```sh
$ npm i -g @tygen/reflector @tygen/html
$ tygen generate . --out docsite --with @tygen/html
```

Error:
```
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@tygen/reflector/lib/helpers.js:13:11)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
```

**Comment by s-panferov** [comment]
@RikkiGibson sorry, currently the project is broken. First working version expected to be ready in a week or so.
